version: 2

run:
  timeout: 120s
linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - nlreturn
    - whitespace
    - unparam
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - durationcheck
    - errname
    - nilerr

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: unused-parameter
      - name: empty-block
        disabled: true
      - name: indent-error-flow
        disabled: true