run:
  timeout: 120s
linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - revive # replacement for golint
    - govet
    - staticcheck
    - nlreturn
    - whitespace
    - wsl
    - unparam
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - durationcheck
    - errname
    - nilerr