selectionColor: green
directoryColor: cyan
sizeStyle: white
logErrorColor: red
logWarningColor: yellow
logInfoColor: green
focusBg: black
focusFg: blue
showHidden: false
indexHeader: index
indexPercentage: 10
pathHeader: ╭──── path
pathPercentage: 70
sizeHeader: size
sizePercentage: 20
pathPrefix: ├─
pathSuffix: ╰─
focusPrefix: '▸['
focusSuffix: ']'
selectionPrefix: '{'
selectionSuffix: '}'
folderIcon: 
fileIcon: 
logErrorFormat: '[ERROR] '
logWarningFormat: '[WARNING] '
logInfoFormat: '[INFO] '
customModeConfigs:
  go-to:
    keyBindings:
      onKeys:
        '~':
          help: Home
          messages:
            - name: ChangeDirectory
              args:
                - /Users/dinhhuy258
            - name: PopMode
              args: []
        D:
          help: Documents
          messages:
            - name: ChangeDirectory
              args:
                - /Users/dinhhuy258/Documents
            - name: PopMode
              args: []
        d:
          help: Downloads
          messages:
            - name: ChangeDirectory
              args:
                - /Users/dinhhuy258/Downloads
            - name: PopMode
              args: []
        g:
          help: focus first
          messages:
            - name: FocusFirst
              args: []
            - name: PopMode
              args: []
        h:
          help: Desktop
          messages:
            - name: ChangeDirectory
              args:
                - /Users/dinhhuy258/Desktop
            - name: PopMode
              args: []
        ctrl+c:
          help: quit
          messages:
            - name: Quit
              args: []
        w:
          help: Workspace
          messages:
            - name: ChangeDirectory
              args:
                - /Users/dinhhuy258/Workspace
            - name: PopMode
              args: []
      default:
        help: cancel
        messages:
          - name: PopMode
            args: []
builtinModeConfigs:
  default:
    keyBindings:
      onKeys:
        G:
          help: focus last
          messages:
            - name: FocusLast
        g:
          help: go to
          messages:
            - name: SwitchMode
              args:
                - go-to
        /:
          help: search
          messages:
            - name: BashExec
              args:
                - |
                  SELECTED=$(ls | fzf --no-sort)
                  if [ "$SELECTED" ]; then
                    echo FocusPath "'"$PWD/$SELECTED"'" >> "${FM_PIPE_MSG_IN:?}"
                  fi
      default: null
