selectionColor: green
logErrorColor: red
logWarningColor: yellow
logInfoColor: green
focusBg: black
focusFg: blue
showHidden: false
indexHeader: index
indexPercentage: 10
pathHeader: ╭──── path
pathPercentage: 65
fileModeHeader: permissions
fileModePercentage: 15
sizeHeader: size
sizePercentage: 10
pathPrefix: ├─
pathSuffix: ╰─
focusPrefix: '▸['
focusSuffix: ']'
selectionPrefix: '{'
selectionSuffix: '}'
logErrorFormat: '[ERROR] '
logWarningFormat: '[WARNING] '
logInfoFormat: '[INFO] '
nodeTypes:
  extensions:
    .go:
      icon: 
    .c:
      icon: 
    .cc:
      icon: 
    .cpp:
      icon: 
    .h:
      icon: 
    .hh:
      icon: 
    .hpp:
      icon: 
    .css:
      icon: 
    .html:
      icon: 
    .java:
      icon: 
    .js:
      icon: 
    .json:
      icon: 
    .lua:
      icon: 
    .md:
      icon: 
    .php:
      icon: 
    .py:
      icon: 
    .rb:
      icon: 
    .ts:
      icon: 
    .vim:
      icon: 
    .midi:
      icon: 
    .mp3:
      icon: 
    .m4a:
      icon: 
    .mid:
      icon: 
    .flac:
      icon: 
    .flv:
      icon: 
    .mp4:
      icon: 
    .mpeg:
      icon: 
    .gif:
      icon: 
    .mjpeg:
      icon: 
    .mjpg:
      icon: 
    .jpeg:
      icon: 
    .jpg:
      icon: 
    .7z:
      icon: 
    .rar:
      icon: 
    .jar:
      icon: 
    .zip:
      icon: 
    .tar:
      icon: 
    .zsh:
      icon: 
    .sh:
      icon: 
    .bash:
      icon: 
customModeConfigs:
  go-to:
    keyBindings:
      onKeys:
        '~':
          help: Home
          messages:
            - name: ChangeDirectory
              args:
                - /Users/dinhhuy258
            - name: PopMode
              args: []
        D:
          help: Documents
          messages:
            - name: ChangeDirectory
              args:
                - /Users/dinhhuy258/Documents
            - name: PopMode
              args: []
        d:
          help: Downloads
          messages:
            - name: ChangeDirectory
              args:
                - /Users/dinhhuy258/Downloads
            - name: PopMode
              args: []
        g:
          help: focus first
          messages:
            - name: FocusFirst
              args: []
            - name: PopMode
              args: []
        h:
          help: Desktop
          messages:
            - name: ChangeDirectory
              args:
                - /Users/dinhhuy258/Desktop
            - name: PopMode
              args: []
        ctrl+c:
          help: quit
          messages:
            - name: Quit
              args: []
        w:
          help: Workspace
          messages:
            - name: ChangeDirectory
              args:
                - /Users/dinhhuy258/Workspace
            - name: PopMode
              args: []
      default:
        help: cancel
        messages:
          - name: PopMode
            args: []
  yarn:
    keyBindings:
      onKeys:
        'p':
          help: yarn path
          messages:
            - name: BashExecSilently
              args:
                - |
                  FOCUS="${FM_FOCUS_PATH}"
                  if [ "$FOCUS" ]; then
                    echo -n $FOCUS | pbcopy -selection clipboard
                    echo LogSuccess "'"$FOCUS was coppied to clipboard"'" >> "${FM_PIPE_MSG_IN:?}"
                  fi

                  echo PopMode >> "${FM_PIPE_MSG_IN:?}"
        'n':
          help: yarn name
          messages:
            - name: BashExecSilently
              args:
                - |
                  FOCUS="${FM_FOCUS_PATH}"
                  if [ "$FOCUS" ]; then
                    echo -n $(basename $FOCUS) | pbcopy -selection clipboard
                    echo LogSuccess "'"$(basename "$FOCUS") was coppied to clipboard"'" >> "${FM_PIPE_MSG_IN:?}"
                  fi

                  echo PopMode >> "${FM_PIPE_MSG_IN:?}"
        'd':
          help: yarn directory
          messages:
            - name: BashExecSilently
              args:
                - |
                  FOCUS="${FM_FOCUS_PATH}"
                  if [ "$FOCUS" ]; then
                    echo -n $(dirname $FOCUS) | pbcopy -selection clipboard
                    echo LogSuccess "'"$(dirname "$FOCUS") was coppied to clipboard"'" >> "${FM_PIPE_MSG_IN:?}"
                  fi

                  echo PopMode >> "${FM_PIPE_MSG_IN:?}"
      default:
        help: cancel
        messages:
          - name: PopMode
            args: []
  open:
    keyBindings:
      onKeys:
        'f':
          help: open in Finder
          messages:
            - name: BashExecSilently
              args:
                - |
                  FOCUS="${FM_FOCUS_PATH}"
                  if [ "$FOCUS" ]; then
                    open -R "${FOCUS}"
                  fi

                  echo PopMode >> "${FM_PIPE_MSG_IN:?}"
        'c':
          help: open in Visual Studio Code
          messages:
            - name: BashExecSilently
              args:
                - |
                  FOCUS="${FM_FOCUS_PATH}"
                  if [ "$FOCUS" ]; then
                    open -a "Visual Studio Code" "${FOCUS}"
                  fi

                  echo PopMode >> "${FM_PIPE_MSG_IN:?}"
        'o':
          help: open
          messages:
            - name: BashExec
              args:
                - |
                  FOCUS="${FM_FOCUS_PATH}"
                  if [ "$FOCUS" ]; then
                    case $(file --mime-type ${FOCUS} -b) in
                        text/*) nvim ${FOCUS};;
                        application/json) nvim ${FOCUS};;
                        *) open "${FOCUS}"
                    esac
                  fi

                  echo PopMode >> "${FM_PIPE_MSG_IN:?}"
      default:
        help: cancel
        messages:
          - name: PopMode
            args: []
builtinModeConfigs:
  default:
    keyBindings:
      onKeys:
        G:
          help: focus last
          messages:
            - name: FocusLast
        g:
          help: go to
          messages:
            - name: SwitchMode
              args:
                - go-to
        o:
          help: open
          messages:
            - name: SwitchMode
              args:
                - open
        y:
          help: yarn
          messages:
            - name: SwitchMode
              args:
                - yarn
        /:
          help: search
          messages:
            - name: BashExec
              args:
                - |
                  SELECTED=$(ls | fzf --no-sort)
                  if [ "$SELECTED" ]; then
                    echo FocusPath "'"$PWD/$SELECTED"'" >> "${FM_PIPE_MSG_IN:?}"
                  fi
      default: null
