package key

import "github.com/dinhhuy258/gocui"

var keyMapReversed = map[gocui.Key]string{
	gocui.KeyF1:          "f1",
	gocui.KeyF2:          "f2",
	gocui.KeyF3:          "f3",
	gocui.KeyF4:          "f4",
	gocui.KeyF5:          "f5",
	gocui.KeyF6:          "f6",
	gocui.KeyF7:          "f7",
	gocui.KeyF8:          "f8",
	gocui.KeyF9:          "f9",
	gocui.KeyF10:         "f10",
	gocui.KeyF11:         "f11",
	gocui.KeyF12:         "f12",
	gocui.KeyInsert:      "insert",
	gocui.KeyDelete:      "delete",
	gocui.KeyHome:        "home",
	gocui.KeyEnd:         "end",
	gocui.KeyPgup:        "pgup",
	gocui.KeyPgdn:        "pgdown",
	gocui.KeyArrowUp:     "▲",
	gocui.KeyArrowDown:   "▼",
	gocui.KeyArrowLeft:   "◄",
	gocui.KeyArrowRight:  "►",
	gocui.KeyTab:         "tab",        // ctrl+i
	gocui.KeyEnter:       "enter",      // ctrl+m
	gocui.KeyEsc:         "esc",        // ctrl+[, ctrl+3
	gocui.KeyBackspace:   "backspace",  // ctrl+h
	gocui.KeyCtrlSpace:   "ctrl+space", // ctrl+~, ctrl+2
	gocui.KeyCtrlSlash:   "ctrl+/",     // ctrl+_
	gocui.KeySpace:       "space",
	gocui.KeyCtrlA:       "ctrl+a",
	gocui.KeyCtrlB:       "ctrl+b",
	gocui.KeyCtrlC:       "ctrl+c",
	gocui.KeyCtrlD:       "ctrl+d",
	gocui.KeyCtrlE:       "ctrl+e",
	gocui.KeyCtrlF:       "ctrl+f",
	gocui.KeyCtrlG:       "ctrl+g",
	gocui.KeyCtrlJ:       "ctrl+j",
	gocui.KeyCtrlK:       "ctrl+k",
	gocui.KeyCtrlL:       "ctrl+l",
	gocui.KeyCtrlN:       "ctrl+n",
	gocui.KeyCtrlO:       "ctrl+o",
	gocui.KeyCtrlP:       "ctrl+p",
	gocui.KeyCtrlQ:       "ctrl+q",
	gocui.KeyCtrlR:       "ctrl+r",
	gocui.KeyCtrlS:       "ctrl+s",
	gocui.KeyCtrlT:       "ctrl+t",
	gocui.KeyCtrlU:       "ctrl+u",
	gocui.KeyCtrlV:       "ctrl+v",
	gocui.KeyCtrlW:       "ctrl+w",
	gocui.KeyCtrlX:       "ctrl+x",
	gocui.KeyCtrlY:       "ctrl+y",
	gocui.KeyCtrlZ:       "ctrl+z",
	gocui.KeyCtrl4:       "ctrl+4", // ctrl+\
	gocui.KeyCtrl5:       "ctrl+5", // ctrl+]
	gocui.KeyCtrl6:       "ctrl+6",
	gocui.KeyCtrl8:       "ctrl+8",
	gocui.MouseWheelUp:   "mouse wheel up",
	gocui.MouseWheelDown: "mouse wheel down",
}

var keymap = map[string]Key{
	"ctrl+a":     toKey(gocui.KeyCtrlA),
	"ctrl+b":     toKey(gocui.KeyCtrlB),
	"ctrl+c":     toKey(gocui.KeyCtrlC),
	"ctrl+d":     toKey(gocui.KeyCtrlD),
	"ctrl+e":     toKey(gocui.KeyCtrlE),
	"ctrl+f":     toKey(gocui.KeyCtrlF),
	"ctrl+g":     toKey(gocui.KeyCtrlG),
	"ctrl+h":     toKey(gocui.KeyCtrlH),
	"ctrl+i":     toKey(gocui.KeyCtrlI),
	"ctrl+j":     toKey(gocui.KeyCtrlJ),
	"ctrl+k":     toKey(gocui.KeyCtrlK),
	"ctrl+l":     toKey(gocui.KeyCtrlL),
	"ctrl+m":     toKey(gocui.KeyCtrlM),
	"ctrl+n":     toKey(gocui.KeyCtrlN),
	"ctrl+o":     toKey(gocui.KeyCtrlO),
	"ctrl+p":     toKey(gocui.KeyCtrlP),
	"ctrl+q":     toKey(gocui.KeyCtrlQ),
	"ctrl+r":     toKey(gocui.KeyCtrlR),
	"ctrl+s":     toKey(gocui.KeyCtrlS),
	"ctrl+t":     toKey(gocui.KeyCtrlT),
	"ctrl+u":     toKey(gocui.KeyCtrlU),
	"ctrl+v":     toKey(gocui.KeyCtrlV),
	"ctrl+w":     toKey(gocui.KeyCtrlW),
	"ctrl+x":     toKey(gocui.KeyCtrlX),
	"ctrl+y":     toKey(gocui.KeyCtrlY),
	"ctrl+z":     toKey(gocui.KeyCtrlZ),
	"ctrl+~":     toKey(gocui.KeyCtrlTilde),
	"ctrl+2":     toKey(gocui.KeyCtrl2),
	"ctrl+3":     toKey(gocui.KeyCtrl3),
	"ctrl+4":     toKey(gocui.KeyCtrl4),
	"ctrl+5":     toKey(gocui.KeyCtrl5),
	"ctrl+6":     toKey(gocui.KeyCtrl6),
	"ctrl+7":     toKey(gocui.KeyCtrl7),
	"ctrl+8":     toKey(gocui.KeyCtrl8),
	"ctrl+space": toKey(gocui.KeyCtrlSpace),
	"ctrl+\\":    toKey(gocui.KeyCtrlBackslash),
	"ctrl+[":     toKey(gocui.KeyCtrlLsqBracket),
	"ctrl+]":     toKey(gocui.KeyCtrlRsqBracket),
	"ctrl+/":     toKey(gocui.KeyCtrlSlash),
	"ctrl+_":     toKey(gocui.KeyCtrlUnderscore),
	"backspace":  toKey(gocui.KeyBackspace2),
	"tab":        toKey(gocui.KeyTab),
	"enter":      toKey(gocui.KeyEnter),
	"esc":        toKey(gocui.KeyEsc),
	"space":      toKey(gocui.KeySpace),
	"f1":         toKey(gocui.KeyF1),
	"f2":         toKey(gocui.KeyF2),
	"f3":         toKey(gocui.KeyF3),
	"f4":         toKey(gocui.KeyF4),
	"f5":         toKey(gocui.KeyF5),
	"f6":         toKey(gocui.KeyF6),
	"f7":         toKey(gocui.KeyF7),
	"f8":         toKey(gocui.KeyF8),
	"f9":         toKey(gocui.KeyF9),
	"f10":        toKey(gocui.KeyF10),
	"f11":        toKey(gocui.KeyF11),
	"f12":        toKey(gocui.KeyF12),
	"insert":     toKey(gocui.KeyInsert),
	"delete":     toKey(gocui.KeyDelete),
	"home":       toKey(gocui.KeyHome),
	"end":        toKey(gocui.KeyEnd),
	"pgup":       toKey(gocui.KeyPgup),
	"pgdown":     toKey(gocui.KeyPgdn),
	"up":         toKey(gocui.KeyArrowUp),
	"down":       toKey(gocui.KeyArrowDown),
	"left":       toKey(gocui.KeyArrowLeft),
	"right":      toKey(gocui.KeyArrowRight),
}

// toKey convert to gocui key to key
func toKey(key gocui.Key) Key {
	return Key{
		Key: key,
		Ch:  0,
		Mod: gocui.ModNone,
	}
}
