name: CICD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # Setup Go
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Run linters
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41
  test:
    runs-on: ubuntu-latest
    steps:
    # Setup Go
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Run tests
    - name: Run tests
      run: go test ./...

